apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: collaboration-service
  name: collaboration-service
  namespace: peerprep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collaboration-service
  template:
    metadata:
      labels:
        app: collaboration-service
    spec:
      containers:
      - image: registry.digitalocean.com/peerprep/collaboration-service@sha256:8b3947d139ab12ba8dad29796d3ed221569c0e86c8fb05fce0c58b6fdafd8eaf
        imagePullPolicy: Always
        name: collaboration-service
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      restartPolicy: Always
status: {}