apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: communication-service
  name: communication-service
  namespace: peerprep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: communication-service
  template:
    metadata:
      labels:
        app: communication-service
    spec:
      containers:
      - image: registry.digitalocean.com/peerprep/communication-service@sha256:cbcbacc34763cefb5fe2855b11e1237336adb9857769ba8beb2bf3e69f0435c6
        imagePullPolicy: Always
        name: communication-service
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      restartPolicy: Always
status: {}