apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: matching-service
  name: matching-service
  namespace: peerprep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matching-service
  template:
    metadata:
      labels:
        app: matching-service
    spec:
      containers:
      - image: registry.digitalocean.com/peerprep/matching-service@sha256:9c2d45cde579cd9d280d9eda5a270c2e4dee0d1de818628d5ea0c6493a3aef2a
        imagePullPolicy: IfNotPresent
        name: matching-service
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      restartPolicy: Always
status: {}
