apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: question-service
  name: question-service
  namespace: peerprep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: question-service
  template:
    metadata:
      labels:
        app: question-service
    spec:
      containers:
      - image: registry.digitalocean.com/peerprep/question-service@sha256:4b6a6def489cd2fdd3827678d5c3fb148f8f7e6d695ed6472aec049c6cd7f3fc
        imagePullPolicy: Always
        name: question-service
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      restartPolicy: Always
status: {}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: question-hpa
  namespace: peerprep
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: question-service
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
