apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: question-service
  name: question-service
  namespace: peerprep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: question-service
  template:
    metadata:
      labels:
        app: question-service
    spec:
      containers:
      - image: registry.digitalocean.com/peerprep/question-service@sha256:02595fe5e7d8ee4160e297949f4edf2ff10404ab06682cdbb744d77fd73bea50
        imagePullPolicy: Always
        name: question-service
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
      restartPolicy: Always
status: {}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: question-hpa
  namespace: peerprep
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: question-service
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
